name: "TechMarket - Main CI/CD Pipeline"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  job-build:
    uses: ./.github/workflows/templates/build.yml
    with:
      node-version: "20"

  job-test:
    needs: job-build
    uses: ./.github/workflows/templates/test.yml
    with:
      node-version: "20"

  job-deploy:
    needs: job-test
    uses: ./.github/workflows/templates/deploy.yml
    with:
      environment: "Production"
    secrets:
      aws-access-key-id: ${{ secrets.aws-access-key-id }}
      aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      aws-session-token: ${{ secrets.aws-session-token }}
