name: "template - deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Entorno de destino (dev, staging, prod)"
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-session-token:
        required: true

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-session-token: ${{ secrets.aws-session-token }}
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0" # O la versión que prefieras
        terraform_wrapper: false
        
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -var="environment=${{ inputs.environment }}" -auto-approve

  
    - name: Obtener nombre del bucket
      id: get_bucket
      run: |
        BUCKET=$(terraform output -raw s3_bucket_name)
        echo "BUCKET_NAME=$BUCKET" >> $GITHUB_ENV
       
    - name: Deploy to S3
      run: |
        echo "Desplegando en el entorno: ${{ inputs.environment }}"
        
        aws s3 sync . s3://${{ env.BUCKET_NAME }} --exclude ".git*"
