name: "template - deploy"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Entorno de destino (dev, staging, prod)"
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-session-token:
        required: true

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-session-token: ${{ secrets.aws-session-token }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"
        terraform_wrapper: false

    # 1. Vaciar el bucket manualmente (S3 no deja borrar buckets con archivos)
    - name: Empty S3 Bucket
      run: |
        aws s3 rm s3://techmarket-app-production-202623457csgfhvsdzhgjstuey9z --recursive || echo "Bucket no encontrado o ya vacío"

    # 2. Ejecutar la destrucción total
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -var="environment=${{ inputs.environment }}" -auto-approve
